export const clubs = [
    {
        id: 1,
        subject: "Tennis",
        location: "Burjuman",
        price: 200,
        availability: 0,
        image: "images/tennis.png",
        rating: 0,
    },
    {
        id: 2,
        subject: "Karate",
        location: "Al Barsha",
        price: 180,
        availability: 4,
        image: "images/karate.jpg",
        rating: 0,
    },
    {
        id: 3,
        subject: "Dance",
        location: "Al Rigga",
        price: 220,
        availability: 1,
        image: "images/dance.png",
        rating: 0,
    },
    {
        id: 4,
        subject: "Cooking",
        location: "Al Khail",
        price: 400,
        availability: 3,
        image: "images/cooking.png",
        rating: 0,
    },
    {
        id: 5,
        subject: "Music",
        location: "Al Majaz",
        price: 350,
        availability: 2,
        image: "images/music.jpg",
        rating: 0,
    },
    {
        id: 6,
        subject: "Debate",
        location: "Deira",
        price: 270,
        availability: 3,
        image: "images/debate.jpg",
        rating: 0,
    },
    {
        id: 7,
        subject: "Technology",
        location: "Expo City",
        price: 190,
        availability: 4,
        image: "images/tech.png",
        rating: 0,
    },
    {
        id: 8,
        subject: "Art",
        location: "Emirates Hills",
        price: 260,
        availability: 1,
        image: "images/art.jpg",
        rating: 0,
    },
    {
        id: 9,
        subject: "Photography",
        location: "Palm Jumeirah",
        price: 320,
        availability: 6,
        image: "images/photography.jpg",
        rating: 0,
    },
    {
        id: 10,
        subject: "Gaming",
        location: "Khalifa Street",
        price: 340,
        availability: 8,
        image: "images/gaming.jpg",
        rating: 0,
    }
];
